services:
  - type: web
    name: lois-agent-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python agent_fixed.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: LANGSMITH_API_KEY  
        sync: false
      - key: LANGCHAIN_TRACING_V2
        value: true
      - key: LANGCHAIN_PROJECT
        value: deepagents